### ISSUE TITLE
[TODO] Enhancements

### ISSUE THREAD

**Issue by pheerai** [f3l/f3lcites#4]
The following things shoulb be done:
- [x] Command-line arguments for port and hosts
- [x] Split all-cites view (only view 20 at a time)
- [ ] Recheck for GDC-bug
- [x] CSS
- [ ] Website texts

**Comment by pheerai** [comment]
Splitted this one up into #5 #6 #7 and #8
